/************************************************************
 Listing 1
 
 File        : internal.h

 Author      : Matt Weisfeld

 Description : Definitions for internal application.
************************************************************/
#define WM_FILE_NEW		100
#define WM_FILE_OPEN		101
#define WM_FILE_SAVE		102
#define WM_FILE_SAVE_AS		103
#define WM_FILE_SAVE_ALL	104
#define WM_FILE_PRINT		105
#define WM_FILE_PRINTER_SETUP	106
#define WM_FILE_EXIT		107
#define WM_EDIT_UNDO		108
#define WM_EDIT_REDO		109
#define WM_EDIT_CUT		110
#define WM_EDIT_COPY		111
#define WM_EDIT_PASTE		112
#define WM_EDIT_CLEAR		113
